version: "3.3"
services:
  app:
    container_name: knowledge-website
    image: knowledge-website
    restart: always
    build:
      context: .
    volumes: 
      - ./src:/app/src
    ports:
      - 172.17.0.1:3000:3000
    environment:
      DOMAIN: https://knowledge-website-u16.vm.elestio.app
    env_file:
      - .env


